### ISSUE TITLE
User Desires Checklist

### ISSUE THREAD

**Issue by Danziger** [helloswyg/autoshapes-example#3]
Checklist to review how or if the library can address certain possible user needs / requirements easily.

These could be eventually turn into examples/demos or be integrated into the demo page.

- [ ] I want some continuous vertical curvy lines at the sides of the page (no or only a few loops).
- [ ] I want the lines to fill in progressively.
- [ ] I want some (2-3 per viewport) large blobs behind my content.
- [ ] I want to fill in an area with N (24-32) small loops.
- [ ] I want to fill in an area with N (24-32) small lines (like pen marks).
- [ ] I want to fill in an area with multicolor confetti.

**Comment by vincentropy** [comment]
- [ ] I want one blob behind my content that matches the size of my content
- [ ] I want one huge blob (more than screen height) partially off the side of the screen
- [ ] I want a horizontal loopy line as a separator between pieces of content (e.g. section on the page) 
- [ ] I want a huge loopy line in the background of all my content stretching vertically along the entire page
